chore: Switching to custom ansible-lint workflow
Signed-off-by: Steffen Scheib <steffen@scheib.me>

diff --git a/.github/workflows/ansible-lint.yml b/.github/workflows/ansible-lint.yml
--- a/.github/workflows/ansible-lint.yml
+++ b/.github/workflows/ansible-lint.yml
@@ -41,10 +41,55 @@ jobs:
             github.com:443
             pypi.org:443
             raw.githubusercontent.com:443
+            www.python.org:443
 
       - name: 'Checkout code'
         uses: 'actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683' # v4.2.2
 
+      - name: 'Install Python'
+        uses: 'actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065' # v5.6.0
+        with:
+          # renovate dep: datasource=python-version versioning=python depName=python
+          python-version: '3.13.3'
+
+      - name: 'Install ansible-core and ansible-lint'
+        shell: 'bash'
+        run: |
+          # fail if:
+          # - a variable is unbound
+          # - any command fails
+          # - a command in a pipe fails
+          # - a command in a sub-shell fails
+          set -Eeuo pipefail
+
+          # enable debug if runner runs in debug
+          [[ "${{ runner.debug }}" -ne 1 ]] || {
+            echo "INFO: Enabling bash trace";
+            set -x;
+          };
+
+          # renovate: datasource=pypi
+          pip3 install ansible-core==2.18.5
+
+          # renovate: datasource=pypi
+          pip3 install ansible-lint==25.4.0
+
       - name: 'Run ansible-lint'
-        uses: 'ansible/ansible-lint@49ded6a7e4f3acf6b1eb4b3aa2796d84b5faa63a' # v25.1.3
+        shell: 'bash'
+        run: |
+          # fail if:
+          # - a variable is unbound
+          # - any command fails
+          # - a command in a pipe fails
+          # - a command in a sub-shell fails
+          set -Eeuo pipefail
+
+          # enable debug if runner runs in debug
+          [[ "${{ runner.debug }}" -ne 1 ]] || {
+            echo "INFO: Enabling bash trace";
+            set -x;
+            declare __DEBUG="-vvvv"
+          };
+
+          ansible-lint "${__DEBUG:=}"
 ...
