ci: Fixing if statement
Signed-off-by: Steffen Scheib <steffen@scheib.me>

diff --git a/.github/workflows/docs_image.yml b/.github/workflows/docs_image.yml
--- a/.github/workflows/docs_image.yml
+++ b/.github/workflows/docs_image.yml
@@ -230,6 +230,9 @@ jobs:
 
       - name: 'Get digest of the test image'
         run: |
+          # fail if a variable is unbound or any command fails, as well as make pipes fail
+          set -eux && set -o pipefail
+
           # tr -d '\0' is required to avoid this warning in BASH:
           # warning: command substitution: ignored null byte in input
           #
@@ -247,7 +250,7 @@ jobs:
                  "${{ needs.prepare-vars.outputs.current-digest }}"
 
           declare publishImage="false"
-          [[ ${{ needs.prepare-vars.outputs.current-digest }} == "${testImageDigest}" ]]; || {
+          [[ ${{ needs.prepare-vars.outputs.current-digest }} == "${testImageDigest}" ]] || {
             echo "INFO: Digest are not identical, will publish a new version";
             publishImage="true";
           };
