ci: Adding shell and bash flags to each run step
Signed-off-by: Steffen Scheib <steffen@scheib.me>

diff --git a/.github/workflows/kics.yml b/.github/workflows/kics.yml
--- a/.github/workflows/kics.yml
+++ b/.github/workflows/kics.yml
@@ -43,7 +43,22 @@ jobs:
           persist-credentials: false
 
       - name: 'Create results directory'
-        run: 'mkdir -p results'
+        shell: 'bash'
+        run: |
+          # fail if:
+          # - a variable is unbound
+          # - any command fails
+          # - a command in a pipe fails
+          # - a command in a sub-shell fails
+          set -Eeuo pipefail
+
+          # enable debug if runner runs in debug
+          [[ "${{ runner.debug }}" -ne 1 ]] || {
+            echo "INFO: Enabling bash trace";
+            set -x;
+          };
+
+          mkdir -p results
 
       - name: 'Run KICS scan'
         uses: 'checkmarx/kics-github-action@530ac1f8efe6202b0f12c9a6e952597ae707b755' # v2.1.2
diff --git a/.github/workflows/molecule_certified_ees.yml b/.github/workflows/molecule_certified_ees.yml
--- a/.github/workflows/molecule_certified_ees.yml
+++ b/.github/workflows/molecule_certified_ees.yml
@@ -115,6 +115,13 @@ jobs:
         id: 'secret-check'
         shell: 'bash'
         run: |
+          # fail if:
+          # - a variable is unbound
+          # - any command fails
+          # - a command in a pipe fails
+          # - a command in a sub-shell fails
+          set -Eeuo pipefail
+
           (
             [[ "${{ secrets.CRC_USERNAME }}" != '' ]] &&
             [[ "${{ secrets.CRC_PASSWORD }}" != '' ]]
@@ -151,6 +158,19 @@ jobs:
         id: 'cache-check'
         shell: 'bash'
         run: |
+          # fail if:
+          # - a variable is unbound
+          # - any command fails
+          # - a command in a pipe fails
+          # - a command in a sub-shell fails
+          set -Eeuo pipefail
+
+          # enable debug if runner runs in debug
+          [[ "${{ runner.debug }}" -ne 1 ]] || {
+            echo "INFO: Enabling bash trace";
+            set -x;
+          };
+
           (
             [[ "${{ github.event_name }}" != "schedule" ]] &&
             [[ "${{ github.event.schedule }}" != "30 2 * * 1" ]]
diff --git a/.github/workflows/molecule_community_ees.yml b/.github/workflows/molecule_community_ees.yml
--- a/.github/workflows/molecule_community_ees.yml
+++ b/.github/workflows/molecule_community_ees.yml
@@ -118,12 +118,40 @@ jobs:
 
       - name: 'Install molecule'
         if: "join(matrix.container.molecule, ' ') != ''"
+        shell: 'bash'
         run: |
+          # fail if:
+          # - a variable is unbound
+          # - any command fails
+          # - a command in a pipe fails
+          # - a command in a sub-shell fails
+          set -Eeuo pipefail
+
+          # enable debug if runner runs in debug
+          [[ "${{ runner.debug }}" -ne 1 ]] || {
+            echo "INFO: Enabling bash trace";
+            set -x;
+          };
+
           pip3 install molecule==${{ matrix.container.molecule }}
 
       - name: 'Install additional packages'
         if: "join(matrix.container.additional_packages, ' ') != ''"
+        shell: 'bash'
         run: |
+          # fail if:
+          # - a variable is unbound
+          # - any command fails
+          # - a command in a pipe fails
+          # - a command in a sub-shell fails
+          set -Eeuo pipefail
+
+          # enable debug if runner runs in debug
+          [[ "${{ runner.debug }}" -ne 1 ]] || {
+            echo "INFO: Enabling bash trace";
+            set -x;
+          };
+
           if command dnf 2>&1 > /dev/null; then
             dnf install -y ${{ join(matrix.container.additional_packages, ' ') }}
           elif command microdnf 2>&1 > /dev/null; then
@@ -135,7 +163,21 @@ jobs:
 
       - name: 'Configure podman'
         if: 'matrix.container.configure_podman'
+        shell: 'bash'
         run: |
+          # fail if:
+          # - a variable is unbound
+          # - any command fails
+          # - a command in a pipe fails
+          # - a command in a sub-shell fails
+          set -Eeuo pipefail
+
+          # enable debug if runner runs in debug
+          [[ "${{ runner.debug }}" -ne 1 ]] || {
+            echo "INFO: Enabling bash trace";
+            set -x;
+          };
+
           # install shadow utils
           dnf -y install shadow-utils
           rpm --setcaps shadow-utils 2>/dev/null
@@ -167,7 +209,21 @@ jobs:
                 touch /var/lib/shared/vfs-layers/layers.lock
 
       - name: 'Run molecule'
+        shell: 'bash'
         run: |
+          # fail if:
+          # - a variable is unbound
+          # - any command fails
+          # - a command in a pipe fails
+          # - a command in a sub-shell fails
+          set -Eeuo pipefail
+
+          # enable debug if runner runs in debug
+          [[ "${{ runner.debug }}" -ne 1 ]] || {
+            echo "INFO: Enabling bash trace";
+            set -x;
+          };
+
           # check if any debug options are enabled
           (
             [[ "${{ github.event.inputs.moleculeDebug }}" == "" ]] ||
diff --git a/.github/workflows/renovate.yml b/.github/workflows/renovate.yml
--- a/.github/workflows/renovate.yml
+++ b/.github/workflows/renovate.yml
@@ -79,6 +79,13 @@ jobs:
         id: 'secret-check'
         shell: 'bash'
         run: |
+          # fail if:
+          # - a variable is unbound
+          # - any command fails
+          # - a command in a pipe fails
+          # - a command in a sub-shell fails
+          set -Eeuo pipefail
+
           (
             [[ "${{ secrets.CRC_USERNAME }}" != '' ]] &&
             [[ "${{ secrets.CRC_PASSWORD }}" != '' ]] &&
@@ -126,7 +133,21 @@ jobs:
 
       - name: 'Check User Permission'
         if: "steps.check-access.outputs.require-result == 'false'"
+        shell: 'bash'
         run: |
+          # fail if:
+          # - a variable is unbound
+          # - any command fails
+          # - a command in a pipe fails
+          # - a command in a sub-shell fails
+          set -Eeuo pipefail
+
+          # enable debug if runner runs in debug
+          [[ "${{ runner.debug }}" -ne 1 ]] || {
+            echo "INFO: Enabling bash trace";
+            set -x;
+          };
+
           echo "${{ github.triggering_actor }} does not have permissions on this repo."
           echo "Current permission level is ${{ steps.check-access.outputs.user-permission }}"
           echo "Job originally triggered by ${{ github.actor }}"
@@ -191,13 +212,27 @@ jobs:
           github.event.inputs.repoCache != 'disabled' &&
           github.event.inputs.repoCache != 'reset' &&
           github.event.schedule != '30 0 * * 1'
+        shell: 'bash'
         run: |
-          set -x
-          # Skip if no cache is set, such as the first time it runs.
-          if [ ! -d cache-download ] ; then
-            echo "No cache found."
-            exit 0
-          fi
+          # fail if:
+          # - a variable is unbound
+          # - any command fails
+          # - a command in a pipe fails
+          # - a command in a sub-shell fails
+          set -Eeuo pipefail
+
+          # enable debug if runner runs in debug
+          [[ "${{ runner.debug }}" -ne 1 ]] || {
+            echo "INFO: Enabling bash trace";
+            set -x;
+          };
+
+          # skip is no cache directory is present
+          # that might happen due to the cache being expired or on the first run
+          [[ ! -d "cache-download" ]] || {
+            echo "INFO: No cache found";
+            exit 0;
+          };
 
           # Make sure the directory exists, and extract it there. Note that it's nested in the download directory.
           mkdir -p "${cache_dir}"
@@ -211,16 +246,14 @@ jobs:
           ls -R "${cache_dir}"
 
       - name: 'Authenticate to console.redhat.com'
+        shell: 'bash'
         run: |
-          # exit immediately if a command fails
-          set -o errexit
-
-          # make the whole pipe fail if any commands within the pipe fail
-          set -o pipefail
-
-          # treats unset variables as an error while performing parameter expansion
-          # special parameters $* and $@ are not affected from this
-          set -o nounset
+          # fail if:
+          # - a variable is unbound
+          # - any command fails
+          # - a command in a pipe fails
+          # - a command in a sub-shell fails
+          set -Eeuo pipefail
 
           # set the parameters for curl
           params=(
@@ -263,7 +296,21 @@ jobs:
 
       - name: 'Compress Renovate cache to improve performance'
         if: "github.event.inputs.repoCache != 'disabled'"
+        shell: 'bash'
         run: |
+          # fail if:
+          # - a variable is unbound
+          # - any command fails
+          # - a command in a pipe fails
+          # - a command in a sub-shell fails
+          set -Eeuo pipefail
+
+          # enable debug if runner runs in debug
+          [[ "${{ runner.debug }}" -ne 1 ]] || {
+            echo "INFO: Enabling bash trace";
+            set -x;
+          };
+
           # The -C is important, as otherwise we end up extracting the files with
           # their full path, ultimately leading to a nested directory situation.
           tar -czvf "${cache_archive}" -C "${cache_dir}" .
diff --git a/.github/workflows/wf_call_molecule_certified_ees.yml b/.github/workflows/wf_call_molecule_certified_ees.yml
--- a/.github/workflows/wf_call_molecule_certified_ees.yml
+++ b/.github/workflows/wf_call_molecule_certified_ees.yml
@@ -64,7 +64,21 @@ jobs:
 
       - name: 'Check User Permission'
         if: "steps.check-access.outputs.require-result == 'false'"
+        shell: 'bash'
         run: |
+          # fail if:
+          # - a variable is unbound
+          # - any command fails
+          # - a command in a pipe fails
+          # - a command in a sub-shell fails
+          set -Eeuo pipefail
+
+          # enable debug if runner runs in debug
+          [[ "${{ runner.debug }}" -ne 1 ]] || {
+            echo "INFO: Enabling bash trace";
+            set -x;
+          };
+
           echo "${{ github.triggering_actor }} does not have permissions on this repo."
           echo "Current permission level is ${{ steps.check-access.outputs.user-permission }}"
           echo "Job originally triggered by ${{ github.actor }}"
@@ -154,7 +168,22 @@ jobs:
           node-version: '20.17.0'
 
       - name: 'Install podman'
-        run: 'microdnf install podman -y'
+        shell: 'bash'
+        run: |
+          # fail if:
+          # - a variable is unbound
+          # - any command fails
+          # - a command in a pipe fails
+          # - a command in a sub-shell fails
+          set -Eeuo pipefail
+
+          # enable debug if runner runs in debug
+          [[ "${{ runner.debug }}" -ne 1 ]] || {
+            echo "INFO: Enabling bash trace";
+            set -x;
+          };
+
+          microdnf install podman -y
 
       - name: 'Checkout repository'
         uses: 'actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332' # v4.1.7
@@ -176,13 +205,27 @@ jobs:
         if: >-
           github.event.inputs.repoCache != 'disabled' &&
           github.event.inputs.repoCache != 'reset'
+        shell: 'bash'
         run: |
-          set -x
-          # Skip if no cache is set, such as the first time it runs.
-          if [ ! -d cache-download ] ; then
-            echo "No cache found."
-            exit 0
-          fi
+          # fail if:
+          # - a variable is unbound
+          # - any command fails
+          # - a command in a pipe fails
+          # - a command in a sub-shell fails
+          set -Eeuo pipefail
+
+          # enable debug if runner runs in debug
+          [[ "${{ runner.debug }}" -ne 1 ]] || {
+            echo "INFO: Enabling bash trace";
+            set -x;
+          };
+
+          # skip is no cache directory is present
+          # that might happen due to the cache being expired or on the first run
+          [[ ! -d "cache-download" ]] || {
+            echo "INFO: No cache found";
+            exit 0;
+          };
 
           # Make sure the directory exists, and extract it there. Note that it's nested in the download directory.
           mkdir -p "${cache_dir}"
@@ -190,16 +233,58 @@ jobs:
 
       - name: 'Install additional packages'
         if: "join(matrix.container.additional_packages, ' ') != ''"
+        shell: 'bash'
         run: |
+          # fail if:
+          # - a variable is unbound
+          # - any command fails
+          # - a command in a pipe fails
+          # - a command in a sub-shell fails
+          set -Eeuo pipefail
+
+          # enable debug if runner runs in debug
+          [[ "${{ runner.debug }}" -ne 1 ]] || {
+            echo "INFO: Enabling bash trace";
+            set -x;
+          };
+
           microdnf install -y ${{ join(matrix.container.additional_packages, ' ') }}
 
       - name: 'Install Python packages'
+        shell: 'bash'
         run: |
+          # fail if:
+          # - a variable is unbound
+          # - any command fails
+          # - a command in a pipe fails
+          # - a command in a sub-shell fails
+          set -Eeuo pipefail
+
+          # enable debug if runner runs in debug
+          [[ "${{ runner.debug }}" -ne 1 ]] || {
+            echo "INFO: Enabling bash trace";
+            set -x;
+          };
+
           pip3 install molecule==${{ matrix.container.molecule }}
           mkdir -pv "${cache_dir}"
 
       - name: 'Run molecule'
+        shell: 'bash'
         run: |
+          # fail if:
+          # - a variable is unbound
+          # - any command fails
+          # - a command in a pipe fails
+          # - a command in a sub-shell fails
+          set -Eeuo pipefail
+
+          # enable debug if runner runs in debug
+          [[ "${{ runner.debug }}" -ne 1 ]] || {
+            echo "INFO: Enabling bash trace";
+            set -x;
+          };
+
           # check if any debug options are enabled
           (
             [[ "${{ github.event.inputs.moleculeDebug }}" == "" ]] ||
@@ -218,7 +303,21 @@ jobs:
 
       - name: 'Compress molecule cache to improve performance'
         if: "github.event.inputs.repoCache != 'disabled'"
+        shell: 'bash'
         run: |
+          # fail if:
+          # - a variable is unbound
+          # - any command fails
+          # - a command in a pipe fails
+          # - a command in a sub-shell fails
+          set -Eeuo pipefail
+
+          # enable debug if runner runs in debug
+          [[ "${{ runner.debug }}" -ne 1 ]] || {
+            echo "INFO: Enabling bash trace";
+            set -x;
+          };
+
           # The -C is important, as otherwise we end up extracting the files with
           # their full path, ultimately leading to a nested directory situation.
           tar -czf "${cache_archive}" -C "${cache_dir}" .
