ci: Mounting sarif file read only; Adding settings to KICS workflow
Signed-off-by: Steffen Scheib <steffen@scheib.me>

diff --git a/.github/workflows/kics.yml b/.github/workflows/kics.yml
--- a/.github/workflows/kics.yml
+++ b/.github/workflows/kics.yml
@@ -76,10 +76,17 @@ jobs:
       - name: 'Run KICS scan'
         uses: 'checkmarx/kics-github-action@c456d047c6b73a360a5e1deb892e3f90fa372a04' # v2.1.8
         with:
-          path: './'
-          output_path: 'results'
+          bom: true
+          comments_with_queries: true
           config_path: './kics.config'
+          enable_annotations: true
+          enable_comments: true
+          enable_jobs_summary: true
+          output_path: 'results'
           output_formats: 'sarif'
+          path: './'
+          profiling: 'MEM'
+
 
       - name: 'Scan results/resulits.sarif to ensure it contains no secrets'
         shell: 'bash'
@@ -97,9 +104,10 @@ jobs:
             set -x;
           };
 
-          docker run -v ./results/results.sarif:/scan "${{ env.gitleaks-image }}" detect --source "/scan" --no-git || {
-            echo "ERROR: Secret found, failing workflow";
-            exit 1;
+          docker run -v ./results/results.sarif:/scan:ro "${{ env.gitleaks-image }}" \
+            detect --source "/scan" --no-git || {
+              echo "ERROR: Secret found, failing workflow";
+              exit 1;
           };
 
           ls -la ./results/results.sarif
